### ISSUE TITLE
[Solution] missing declaration for tmKey.cpp compilation

### ISSUE THREAD

**Issue by rndmerle** [etexteditor/e#25]
Hi.

When compiling I still had this error message :
    $ make DEBUG=1
    [CC] tmKey.cpp
    tmKey.cpp: In static member function ‘static void tmKey::BuildMaps()’:
    tmKey.cpp:162: error: ‘_’ was not declared in this scope
    tmKey.cpp: In constructor ‘tmKey::tmKey(const wxString&)’:
    tmKey.cpp:277: error: ‘wxMessageBox’ was not declared in this scope
    tmKey.cpp: In member function ‘void tmKey::UpdateShortcut()’:
    tmKey.cpp:291: error: ‘_’ was not declared in this scope
    tmKey.cpp:292: error: ‘_’ was not declared in this scope
    tmKey.cpp:293: error: ‘_’ was not declared in this scope
    tmKey.cpp:294: error: ‘_’ was not declared in this scope
    tmKey.cpp:300: error: ‘_’ was not declared in this scope
    tmKey.cpp: In member function ‘wxString tmKey::getBinding()’:
    tmKey.cpp:321: error: ‘_’ was not declared in this scope
    tmKey.cpp:322: error: ‘_’ was not declared in this scope
    tmKey.cpp:323: error: ‘_’ was not declared in this scope
    tmKey.cpp: In static member function ‘static bool tmKey::wxkToUni(int, bool, wxChar&)’:
    tmKey.cpp:374: error: ‘gdk_unicode_to_keyval’ was not declared in this scope
    tmKey.cpp:377: error: ‘gdk_keyval_to_upper’ was not declared in this scope
    tmKey.cpp:377: error: ‘gdk_keyval_to_lower’ was not declared in this scope
    tmKey.cpp:378: error: ‘gdk_keyval_to_unicode’ was not declared in this scope
    tmKey.cpp:381: error: ‘wxLogDebug’ was not declared in this scope
    tmKey.cpp: In static member function ‘static bool tmKey::uniToWxk(wxChar, int&, int&)’:
    tmKey.cpp:407: error: ‘gdk_unicode_to_keyval’ was not declared in this scope
    tmKey.cpp:410: error: ‘gdk_keyval_is_upper’ was not declared in this scope
    tmKey.cpp:413: error: ‘gdk_keyval_to_lower’ was not declared in this scope
    tmKey.cpp:415: error: ‘wxLogDebug’ was not declared in this scope
    tmKey.cpp:419: error: ‘gdk_keyval_to_unicode’ was not declared in this scope
    tmKey.cpp:421: error: ‘wxLogDebug’ was not declared in this scope
    make: **\* [.objs.debug/tmKey.o] Error 1

So in the src/tmKey.cpp file, I added :
    #ifdef **WXGTK**
      #include <gdk/gdk.h>
    #endif

```
#include <wx/msgdlg.h>
#include <wx/log.h>
```

And here come a fresh e.debug executable ^_^

**Comment by adamv** [comment]
Fixed in this branch: http://github.com/joeri/e/commit/f4341e93ddb85a534e056b2a1a50a6d118a2109e

**Comment by mattbeedle** [comment]
I'm still experiencing the same issue, even with those changes. (ubuntu 9.04)
